# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Instructions.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ins(object):
    def setupUi(self, ins):
        ins.setObjectName("ins")
        ins.resize(1082, 635)
        self.centralwidget = QtWidgets.QWidget(ins)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_3.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_3.addWidget(self.label_10)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_3.addWidget(self.label_8)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        ins.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ins)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1082, 26))
        self.menubar.setObjectName("menubar")
        ins.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ins)
        self.statusbar.setObjectName("statusbar")
        ins.setStatusBar(self.statusbar)

        self.retranslateUi(ins)
        QtCore.QMetaObject.connectSlotsByName(ins)

    def retranslateUi(self, ins):
        _translate = QtCore.QCoreApplication.translate
        ins.setWindowTitle(_translate("ins", "Instructions"))
        self.label.setText(_translate("ins", "It is a one player game.PLAYER VS COMPUTER.Player has to select from the following choices:Rock,Paper,Pencil and Scissor."))
        self.label_9.setText(_translate("ins", "If the same item is selected by player as well as computer,its a tie.If a rock and scissors are formed, the rock wins, because a rock can smash scissors."))
        self.label_10.setText(_translate("ins", " If scissors and paper are formed, the scissors win, because scissors can cut paper. "))
        self.label_5.setText(_translate("ins", "If paper and a rock are formed, the paper wins, because a sheet of paper can cover a rock. If pencil and paper are formed pencil wins as pencli will write on paper."))
        self.label_8.setText(_translate("ins", "Each time player wins he will get 1 point and it implies same for computer also."))
        self.label_3.setText(_translate("ins", "The one having maximum score at the end of 30 seconds will win."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ins = QtWidgets.QMainWindow()
    ui = Ui_ins()
    ui.setupUi(ins)
    ins.show()
    sys.exit(app.exec_())
